defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":9090"
[web]
#address = ":8081"
[marathon]
endpoint = "http://mesos-master1.mes3.bot.hc.lan:8080,mesos-master2.mes3.bot.hc.lan:8080,mesos-master3.mes3.bot.hc.lan:8080"
watch = true
domain = "mesos-proxy1.mes3.bot.hc.lan"
filename = "marathon.tmpl"
exposedByDefault = true
